using Serenity.Navigation;
using MyPages = SereneMovieTutorial.Default.Pages;
using myController = SereneMovieTutorial.Reports;
//[assembly: NavigationMenu(int.MaxValue, "Movie Database", icon: "fa-film")]
[assembly: NavigationMenu(int.MaxValue -1, "DailyWork", icon: "glyphicon glyphicon-tasks")]
[assembly: NavigationLink(int.MaxValue, "DailyWork/Loading Trip", typeof(MyPages.LoadingTripController), icon: "fas fa-truck")]
[assembly: NavigationMenu(int.MaxValue - 1, "Movie", icon: "glyphicon glyphicon-film")]
[assembly: NavigationLink(int.MaxValue, "Movie/Movies", typeof(MyPages.MovieController), icon: "fa-video-camera")]
[assembly: NavigationLink(int.MaxValue , "Movie/Genre", typeof(MyPages.GenreController), icon: "fa-thumb-tack")]
[assembly: NavigationLink(int.MaxValue , "Movie/Person", typeof(MyPages.PersonController), icon: "fas fa-user")]
[assembly: NavigationMenu(int.MaxValue - 1, "Master", icon: "fas fa-user-circle")]
[assembly: NavigationLink(int.MaxValue, "Master/Employees", typeof(MyPages.EmployeesController), icon: "fas fa-user")]
[assembly: NavigationLink(int.MaxValue, "Master/Plant", typeof(MyPages.PlantController), icon: "fa fa-industry")]
[assembly: NavigationLink(int.MaxValue, "Master/Distict", typeof(MyPages.DistictController), icon: "fa fa-map-marker")]
[assembly: NavigationLink(int.MaxValue, "Master/Destination", typeof(MyPages.DestinationController), icon: "fa fa-location-arrow")]
[assembly: NavigationLink(int.MaxValue, "Master/Expense", typeof(MyPages.ExpenseController), icon: "fa fa-money")]
[assembly: NavigationMenu(int.MaxValue - 1, "Reports", icon: "fas fa-file")]
[assembly: NavigationLink(int.MaxValue, "Master/Vehicle ", typeof(MyPages.VehicleMasterController), icon: "fas fa-truck")]
[assembly: NavigationLink(int.MaxValue, "Master/Owner ", typeof(MyPages.CustomerMasterController), icon: "fas fa-address-card")]
[assembly: NavigationLink(int.MaxValue - 1, "Reports/Generate Report", url: "~/Reports/CustomerVehicleReport/GetCustId", permission: "Reports:CustomerVehicle", icon: "fas fa-address-card")]
[assembly: NavigationLink(int.MaxValue, "Master/Branch", typeof(MyPages.BranchMasterController), icon: "fa fa-industry")]
[assembly: NavigationLink(int.MaxValue, "Master/State", typeof(MyPages.StateMasterController), icon: "fa fa-map")]
[assembly: NavigationLink(int.MaxValue, "Master/Item", typeof(MyPages.ItemMasterController), icon: "fa fa-cube")]
[assembly: NavigationLink(int.MaxValue, "Master/Financial Year", typeof(MyPages.FinancialYearController), icon: "glyphicon glyphicon-calendar")]
[assembly: NavigationLink(int.MaxValue, "Default/Customer", typeof(MyPages.CustomerController), icon: null)]
//[assembly: NavigationMenu(2000, "Default", icon: "fa-folder")]
//[assembly: NavigationLink(2100, "Default/Customer",typeof(MyPages.CustomerController),icon: "fa-users", permission: "Default:Customer:View")]
